[package]
name = "realmlib"
version = "0.1.0"
edition = "2021"

[lib]
name = "realmlib"
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.21"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }